apiVersion: v1
kind: Pod
metadata:
  name: prom-tsdb-importer
  namespace: monitoring
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0          # Run as root user
    runAsGroup: 0
    fsGroup: 0
  containers:
    - name: importer
      image: quay.io/prometheus/prometheus:v3.4.0
      command: ["/bin/sh","-lc"]
      securityContext:
        runAsUser: 0
      args:
        - |
          echo "Waiting for export.om..."
          while [ ! -s /work/export.om ]; do sleep 2; done
          echo "Creating TSDB blocks from OpenMetrics..."
          rm -rf /work/import-blocks && mkdir -p /work/import-blocks
          promtool tsdb create-blocks-from \
            --max-block-duration=48h \
            openmetrics /work/export.om /work/import-blocks
          sleep 300
          chmod 777 /work
          ls -lrt /work/
          head /work/import-blocks
          echo "Copying blocks into PVC..."
          mkdir -p /prometheus
          chmod 777 /prometheus
          ls -lrt /prometheus
          for d in /work/import-blocks/*; do
            [ -d "$d" ] || continue
            cp -a "$d" /prometheus/
          done
          echo "Done. Blocks now in /prometheus:"
          ls -1 /prometheus || true
          # Stay up a bit so you can inspect logs if you want
          sleep 15
      volumeMounts:
        - name: data
          mountPath: /prometheus
        - name: work
          mountPath: /work
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: prometheus-data
    - name: work
      emptyDir: {}
